#
# This job gets installed only if Grafana, Loki and Promtail are enabled.
#
# It's an ephemeral container running at the start and end of each Helm
# deploy and it's used to log at stdout the Helm revision we are
# installing / we finished installing.
#
# This datapoint is useful and can be very helpful as annotation
# in Grafana dashboard.
#
{{- if and .Values.grafana.enabled (and .Values.loki.enabled .Values.promtail.enabled) }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ printf "%s-grafana-annotation-job-post-%s" .Release.Name (now | date "2006-01-02-15-04-05") }}
  labels: {{- include "_snippet-metadata-labels-common" . | nindent 4 }}
  annotations: {{- include "_snippet-metadata-annotations-common" . | nindent 4 }}
    "helm.sh/hook": "post-install,post-upgrade,post-rollback"
    "helm.sh/hook-delete-policy": "hook-succeeded, hook-failed"
spec:
  template:
    metadata:
      name: {{ printf "%s-grafana-annotation-job-post-%s" .Release.Name (now | date "2006-01-02-15-04-05") }}
    spec:
      restartPolicy: Never

      {{- if .Values.busybox.pullSecrets }}
      imagePullSecrets:
        {{- range .Values.busybox.pullSecrets }}
        - name: {{ . }}
        {{- end }}
      {{- end }}

      containers:
      - name: grafana-annotation-job-post
        image: {{ .Values.busybox.image }}
        imagePullPolicy: {{ .Values.busybox.pullPolicy }}
        command:
          - /bin/sh
          - -c
          - |
            echo '{"operation": "helm_release", "operation_stage": "end", "helm_revision": "{{ .Release.Revision }}"}'
{{- end }}
