{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "posthog.fullname" . }}
  labels: {{- include "_snippet-metadata-labels-common" . | nindent 4 }}
  annotations: {{- include "_snippet-metadata-annotations-common" . | nindent 4 }}
    {{- if (eq (include "ingress.type" .) "nginx") }}
    kubernetes.io/ingress.class: "nginx"
    {{- end }}
    {{- if (eq (include "ingress.type" .) "clb") }}
    kubernetes.io/ingress.class: "gce"
    {{- if not (.Values.ingress.gcp.secretName) }}
    networking.gke.io/managed-certificates: "{{ .Release.Name }}-gke-cert"
    {{- end }}
    networking.gke.io/v1beta1.FrontendConfig: "{{ .Release.Name }}-frontend-config"
    {{- if .Values.ingress.gcp.ip_name }}
    kubernetes.io/ingress.global-static-ip-name: {{ .Values.ingress.gcp.ip_name | quote }}
    {{- end }}
   {{- end }}
   {{- if (and (eq (include "ingress.type" .) "nginx") .Values.ingress.nginx.redirectToTLS "true") }}
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_set_headers "Strict-Transport-Security: max-age=30; includeSubDomains";
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
   {{- if eq (include "ingress.letsencrypt" .) "true"}}
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
   {{- end }}
   {{- end }}
   {{- if .Values.ingress.annotations }}
    {{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
   {{- end }}
spec:
  {{- if or (eq (include "ingress.letsencrypt" .) "true") (or (.Values.ingress.secretName) (.Values.ingress.gcp.secretName)) }}
  tls:
  - hosts:
    - {{ .Values.ingress.hostname }}
    {{- if .Values.ingress.secretName }}
    secretName: {{ .Values.ingress.secretName }}
    {{- else if eq (include "ingress.letsencrypt" .) "true" }}
    secretName: nginx-letsencrypt-{{ template "posthog.fullname" . }}
    {{- else }}
    secretName: {{ .Values.ingress.gcp.secretName }}
    {{- end }}
  {{- end }}
  rules:
  {{- if .Values.ingress.hostname }}
    - host: {{ .Values.ingress.hostname }}
      http:
  {{- else }}
    - http:
  {{- end }}
        paths:
          {{- if (ne (include "ingress.type" .) "clb") }}
          - pathType: Prefix
            path: "/"
          {{- else }}
          - pathType: ImplementationSpecific
            path: "/*"
          {{- end }}
            backend:
              service:
                name: {{ template "posthog.fullname" . }}-web
                port:
                  number: {{ .Values.service.externalPort }}
          {{- if (ne (include "ingress.type" .) "clb") }}
          - pathType: Prefix
            path: "/batch"
          {{- else }}
          - pathType: ImplementationSpecific
            path: "/batch/*"
          {{- end }}
            backend: &INGESTION
              service:
                name: {{ template "posthog.fullname" . }}-events
                port:
                  number: {{ .Values.service.externalPort }}
          {{- if (ne (include "ingress.type" .) "clb") }}
          # Match any url with a prefix ending with a forward-slash. Previously
          # we would match without the forward-slash. To ensure that we pick up
          # with the forward-slash omitted we also match Exact. Note that we
          # could use e.g. [ingress-nginx regex support](https://kubernetes.github.io/ingress-nginx/user-guide/ingress-path-matching/#regular-expression-support)
          # but to keep this agnostic we use a combination of Prefix and Exact.
          #
          # NOTE: we still use a Prefix match on paths with a forward-slash,
          # just in case there are cases that we have subpaths for these
          # endpoints that still need to be passed to the `posthog-events` pods.
          - pathType: Prefix
            path: "/capture/"
            backend: *INGESTION
          - pathType: Exact
            path: "/capture"
            backend: *INGESTION

          {{- if .Values.capture.ingress.enabled}}
          - pathType: Prefix
            path: "/i/"
            backend:
              service:
                name: {{ .Values.capture.ingress.service.name }}
                port:
                  number: {{ .Values.capture.ingress.service.port }}
          {{- end }}

          {{- if .Values.decide.ingressEnabled}}
          - pathType: Prefix
            path: "/decide/"
            backend:
              service:
                name: {{ template "posthog.fullname" . }}-decide
                port:
                  number: {{ .Values.service.externalPort }}
          - pathType: Exact
            path: "/decide"
            backend:
              service:
                name: {{ template "posthog.fullname" . }}-decide
                port:
                  number: {{ .Values.service.externalPort }}
          {{- else }}
          - pathType: Prefix
            path: "/decide/"
            backend: *INGESTION
          - pathType: Exact
            path: "/decide"
            backend: *INGESTION
          {{- end }}

          - pathType: Prefix
            path: "/e/"
            backend: *INGESTION
          - pathType: Exact
            path: "/e"
            backend: *INGESTION

          - pathType: Prefix
            path: "/engage/"
            backend: *INGESTION
          - pathType: Exact
            path: "/engage"
            backend: *INGESTION

          - pathType: Prefix
            path: "/track/"
            backend: *INGESTION
          - pathType: Exact
            path: "/track"
            backend: *INGESTION

          {{- if .Values.recordings.ingressEnabled}}
          - pathType: Prefix
            path: "/s/"
            backend:
              service:
                name: {{ template "posthog.fullname" . }}-recordings
                port:
                  number: {{ .Values.service.externalPort }}
          - pathType: Exact
            path: "/s"
            backend:
              service:
                name: {{ template "posthog.fullname" . }}-recordings
                port:
                  number: {{ .Values.service.externalPort }}
          {{- else }}
          - pathType: Prefix
            path: "/s/"
            backend: *INGESTION
          - pathType: Exact
            path: "/s"
            backend: *INGESTION
          {{- end }}

          {{- else }}
          - pathType: ImplementationSpecific
            path: "/capture/*"
            backend: *INGESTION
          - pathType: ImplementationSpecific
            path: "/decide/*"
            backend: *INGESTION
          - pathType: ImplementationSpecific
            path: "/e/*"
            backend: *INGESTION
          - pathType: ImplementationSpecific
            path: "/engage/*"
            backend: *INGESTION
          - pathType: ImplementationSpecific
            path: "/track/*"
            backend: *INGESTION
          - pathType: ImplementationSpecific
            path: "/s/*"
            backend: *INGESTION
          {{- end }}
{{- if .Values.ingress.tls }}
{{ toYaml .Values.ingress.tls | indent 4 }}
{{- end -}}
{{- end -}}
