{{- if .Values.pgbouncer.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "posthog.fullname" . }}-pgbouncer
  labels:
    app: {{ template "posthog.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  type: "ClusterIP"
  ports:
  - port: 6543
    targetPort: 6543
    protocol: TCP
    name: {{ template "posthog.fullname" . }}-pgbouncer
  selector:
    app: {{ template "posthog.fullname" . }}
    role: pgbouncer
{{- end }}
