{{- if .Values.plugins.enabled -}}
# Keep this in sync with `plugins-async-deployment.yaml`
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "posthog.fullname" . }}-plugins
  labels: {{- include "_snippet-metadata-labels-common" . | nindent 4 }}
  annotations: {{- include "_snippet-metadata-annotations-common" . | nindent 4 }}
spec:
  selector:
    matchLabels:
        app: {{ template "posthog.fullname" . }}
        release: "{{ .Release.Name }}"
        role: plugins
  {{- if not .Values.plugins.hpa.enabled }}
  replicas: {{ .Values.plugins.replicacount }}
  {{- end }}
  template:
    metadata:
      annotations:
        checksum/secrets.yaml: {{ include (print $.Template.BasePath "/secrets.yaml") . | sha256sum }}
        {{- if .Values.plugins.podAnnotations }}
        {{- toYaml .Values.plugins.podAnnotations | nindent 8 }}
        {{- end }}
      labels:
        app: {{ template "posthog.fullname" . }}
        release: "{{ .Release.Name }}"
        role: plugins
        {{- if (eq (default .Values.image.tag "none") "latest") }}
        date: "{{ now | unixEpoch }}"
        {{- end }}
        {{- if .Values.plugins.podLabels }}
        {{- toYaml .Values.plugins.podLabels | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ template "posthog.serviceAccountName" . }}
      {{- if .Values.plugins.affinity }}
      affinity:
        {{- toYaml .Values.plugins.affinity | nindent 8 }}
      {{- end }}
      {{- if .Values.plugins.nodeSelector }}
      nodeSelector:
        {{- toYaml .Values.plugins.nodeSelector | nindent 8 }}
      {{- end }}
      {{- if .Values.plugins.tolerations }}
      tolerations:
        {{- toYaml .Values.plugins.tolerations | nindent 8 }}
      {{- end }}
      {{- if .Values.plugins.schedulerName }}
      schedulerName: "{{ .Values.plugins.schedulerName }}"
      {{- end }}
      {{- if .Values.plugins.priorityClassName }}
      priorityClassName: "{{ .Values.plugins.priorityClassName }}"
      {{- end }}
      {{- if .Values.image.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml .Values.image.imagePullSecrets | nindent 8 }}
      {{- end }}
      {{- if .Values.plugins.podSecurityContext.enabled }}
      securityContext: {{- omit .Values.plugins.podSecurityContext "enabled" | toYaml | nindent 8 }}
      {{- end }}
      containers:
      - name: {{ .Chart.Name }}-plugins
        image: {{ template "posthog.image.fullPath" . }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command:
          - ./bin/plugin-server
          - --no-restart-loop
        ports:
        # Expose the port on which the healtchheck endpoint listens
        - containerPort: 6738
        env:
        {{- if .Values.pluginsAsync.enabled }}
        - name: PLUGIN_SERVER_MODE
          value: "ingestion"
        {{- end }}
        # Kafka env variables
        {{- include "snippet.kafka-env" . | nindent 8 }}

        # Object Storage env variables
        {{- include "snippet.objectstorage-env" . | nindent 8 }}

        # Redis env variables
        {{- include "snippet.redis-env" . | nindent 8 }}

        # statsd env variables
        {{- include "snippet.statsd-env" . | nindent 8 }}

        - name: SITE_URL
          value: {{ template "posthog.site.url" . }}
        - name: SENTRY_DSN
          value: {{ .Values.sentryDSN | quote }}
        - name: DEPLOYMENT
          value: {{ template "posthog.deploymentEnv" . }}
        {{- include "snippet.posthog-env" . | indent 8 }}
        {{- include "snippet.postgresql-env" . | nindent 8 }}
        {{- include "snippet.clickhouse-env" . | nindent 8 }}
        - name: CAPTURE_INTERNAL_METRICS
          value: {{ .Values.web.internalMetrics.capture| quote }}
        - name: HELM_INSTALL_INFO
          value: {{ template "posthog.helmInstallInfo" . }}
        {{- if .Values.env }}
        {{- toYaml .Values.env | nindent 8 }}
        {{- end }}
        {{- if .Values.plugins.env }}
        {{- toYaml .Values.plugins.env | nindent 8 }}
        {{- end }}
        livenessProbe:
          exec:
            command:
              #Â Just check that we can at least exec to the container
              - "true"
          failureThreshold: {{ .Values.plugins.livenessProbe.failureThreshold }}
          initialDelaySeconds: {{ .Values.plugins.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.plugins.livenessProbe.periodSeconds }}
          successThreshold: {{ .Values.plugins.livenessProbe.successThreshold }}
          timeoutSeconds: {{ .Values.plugins.livenessProbe.timeoutSeconds }}
        readinessProbe:
          failureThreshold: {{ .Values.plugins.readinessProbe.failureThreshold }}
          httpGet:
            path: /_health
            port: 6738
            scheme: HTTP
          initialDelaySeconds: {{ .Values.plugins.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.plugins.readinessProbe.periodSeconds }}
          successThreshold: {{ .Values.plugins.readinessProbe.successThreshold }}
          timeoutSeconds: {{ .Values.plugins.readinessProbe.timeoutSeconds }}
        resources:
          {{- toYaml .Values.plugins.resources | nindent 12 }}
        {{- if .Values.plugins.securityContext.enabled }}
        securityContext:
          {{- omit .Values.plugins.securityContext "enabled" | toYaml | nindent 12 }}
        {{- end }}
      initContainers:
      {{- include "_snippet-initContainers-wait-for-service-dependencies" . | indent 8 }}
      {{- include "_snippet-initContainers-wait-for-migrations" . | indent 8 }}
{{- end }}
