{{- if .Values.clickhouse.enabled }}
# Template Parameters:
#
# COMMENT=
# NAMESPACE={{ .Values.clickhouse.namespace | default .Release.Namespace }}
# NAME=clickhouse-operator
#
# Setup ServiceAccount
apiVersion: v1
kind: ServiceAccount
metadata:
  name: clickhouse-operator
  namespace: {{ .Values.clickhouse.namespace | default .Release.Namespace }}
  labels:
    clickhouse.altinity.com/chop: 0.18.4

{{- end }}
