cloud: k3s

image:
  tag: latest

ingress:
  type: nginx
  hostname: test.yourcloud.net
  path: /*
  letsencrypt: false
  nginx:
    enabled: false

clickhouseOperator:
  enabled: true
  namespace: default
  storage: 2Gi

postgresql:
  persistence:
    size: 1Gi

redis:
  master:
    persistence:
      size: 1Gi

kafka:
  persistence:
    size: 1Gi

plugins:
  replicacount: 1

worker:
  replicacount: 1

redis:
  usePassword: false
  password: ""

web:
  secureCookies: false
