apiVersion: v2
name: posthog
description: ðŸ¦” PostHog is developer-friendly, open-source product analytics.
icon: https://camo.githubusercontent.com/11f72f57f33d7d34807bafc1314844f7a91bcdea/68747470733a2f2f706f7374686f672d7374617469632d66696c65732e73332e75732d656173742d322e616d617a6f6e6177732e636f6d2f576562736974652d4173736574732f6769746875622d636f7665722e706e67
kubeVersion: ">= 1.19-0 <= 1.22-0"
home: https://posthog.com
sources:
  - https://github.com/PostHog/charts-clickhouse

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
version: 8.0.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application.
appVersion: 1.31.1

dependencies:
  - name: zookeeper
    version: 7.0.5
    repository: https://charts.bitnami.com/bitnami
    condition: zookeeper.enabled
  - name: postgresql
    version: 8.6.1
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: redis
    version: 14.6.2
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
  - name: kafka
    version: 12.6.0
    repository: https://charts.bitnami.com/bitnami
    condition: kafka.enabled
  - name: ingress-nginx
    version: 4.0.13
    repository: https://kubernetes.github.io/ingress-nginx
    condition: ingress.nginx.enabled
    namespace: ingress-nginx
  - name: cert-manager
    version: 1.6.1
    repository: https://charts.jetstack.io
    condition: cert-manager.enabled
    namespace: cert-manager
  - name: prometheus
    version: 14.1.1
    repository: https://prometheus-community.github.io/helm-charts
    condition: prometheus.enabled
  - name: prometheus-statsd-exporter
    version: 0.3.1
    repository: https://prometheus-community.github.io/helm-charts
    condition: statsd.enabled
    alias: statsd

maintainers:
  - name: mariusandra
    email: marius@posthog.com
  - name: timgl
    email: tim@posthog.com
  - name: jams
    email: james.g@posthog.com
  - name: macobo
    email: karl@posthog.com
  - name: tiina
    email: tiina@posthog.com
  - name: guido
    email: guido@posthog.com
  - name: yakko
    email: yakko@posthog.com
